apiVersion: v1
kind: Pod
metadata:
  name: vault-mongo
  labels:
    app: vault-mongo
  annotations:
    vault.hashicorp.com/agent-inject: 'true'
    vault.hashicorp.com/role: 'internal-app'
    vault.hashicorp.com/agent-inject-secret-.env: 'internal/data/database/config'
    vault.hashicorp.com/agent-inject-.env: |
      {{- with secret "internal/data/database/config" -}}
      username:  {{ .Data.username }}
      password:  {{ .Data.password }}
      {{- end -}}
spec:
  serviceAccountName: internal-app
  containers:
    - name: vault-mongo
      image: yuvalammatrix/vault_mongo:image
